### ISSUE TITLE
add bower support

### ISSUE THREAD

**Issue by luisvt** [ngParty/ts-helpers#3]
Please add bower support

**Comment by Hotell** [comment]
bower is dead to me :) you can use `yarn` or PR is more than welcome :)

**Comment by luisvt** [comment]
You are right, bower is dead. And for those wanting to use requireJS with this library my recommendation is to use either cajonjs, browserify, webpack, systemjs or any other commonjs bundler

**Comment by Hotell** [comment]
#HighFive on that ! :)
